DROP TABLE IF EXISTS badges;
DROP TABLE IF EXISTS hasBadges;
DROP TABLE IF EXISTS user;

CREATE TABLE user{
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    status TINYINT NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY(id)
}